server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
#spring
spring:
  application:
    name: weixin-java-cp
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 100MB
  mvc:
    static-path-pattern: /**
#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: "classpath*:mappers/**/*.xml"
#logging
logging:
  config: classpath:logback-spring.xml




