datasource:
  druid:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  master:
    write:
      url: jdbc:mysql://10.100.14.54:3306/dev_devops_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      userName: tyfund_write
      password: 2FhYE9fIAFP1P#Tk
      driverClassName: com.mysql.jdbc.Driver
      validationQuery: SELECT 1 FROM DUAL
    read:
      url: jdbc:mysql://10.100.14.54:3306/dev_devops_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      userName: tyfund_read
      password: 2FhYE9fIAFP1P#Tk
      driverClassName: com.mysql.jdbc.Driver
      validationQuery: SELECT 1 FROM DUAL