server:
  port: 8010
  servlet:
    context-path: /weixin
spring:
  application:
    name: weixin-java-cp
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: "classpath*:mappers/**/*.xml"
