# 数据源
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_devops_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1Qaz@wsx0302
    # druid连接池
    druid:
      initial-size: 5
      max-wait: 60000
      min-idle: 10
      max-active: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query:  SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  #thymeleaf
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
  # redis
#  redis:
#    host:
#    password:


